# Array Indexing and Slicing

In [1]:
# Imports required but not shown in the video lecture.
import numpy

from numpy import array, arange

In [ ]:
print numpy.__version__

Setting Array Elements
======================

Array Indexing
--------------

The elements of one dimensional arrays are accessed exactly elements of a list.  And, the elements are both readable and writable.  Python has zero based indexing, so the 1st element is accessed using `a[0]`.  In this example we are retrieving the index `0` element as well as changing it to the value `10`.   

In [2]:
a = array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [3]:
a[0]

0

In [4]:
a[0] = 10
a

array([10,  1,  2,  3])

Filling an Array with a Single Value
------------------------------------

The `fill` method makes it easy to set all the elements in an array to a single value.  There is also a slicing trick (discussed in more detail later in the lecture) that will do exactly the same thing.

In [5]:
a.fill(0)
a

array([0, 0, 0, 0])

In [6]:
a[:] = 1
a

array([1, 1, 1, 1])

Beware of Type Coercion
-----------------------

Because the individual elements of NumPy arrays are all the same type, values that don't 'fit' into the data type can end up getting truncated.  For example, if you have an array of integers and try to assign a floating point number into it, the decimal portion of the number is simply left off.  Here, we have a 10.6 that is truncated to be 10.  The `fill` method has exactly the same behavior. 

In [7]:
a[0] = 10.6
a

array([10,  1,  1,  1])

In [8]:
a.fill(-4.8)
a

array([-4, -4, -4, -4])

Slicing
-------
Slicing out a set of consecutive values from an array has the following syntax:

    var[lower:upper]

If you think about the indices as 'between' the elements, this is saying return all the elements that fall between the `lower` and `upper` index.  Or, an alternative way of thinking about this is that the returned values will start at the `lower` index and go up to, but not include, the `upper` index.

Slicing can actually take a 3rd value, called the `step` value:

    var[lower:upper:step]

A `step` value of `2` tells Python to skip every other element that it retrieves from the array.   

In [ ]:
a = array([10, 11, 12, 13, 14])
a

In [ ]:
a[1:3]

In [ ]:
a[1:-2]

In [ ]:
a[-4:3]

Omitting Indices
----------------

If you omit the `lower` index, then the slice starts at the beginning of the array and goes up to (but doesn't include) the `upper` index.                           

In [ ]:
a[:3]

Omitting the `upper` index means the slice goes to the end of the array.  

In [ ]:
a[-2:]

If you omit both the `lower` and the `upper` index, then the slice starts at the beginning and goes to the end of the array.  Here, we have also add a `step` value so that every other element is returned.

In [ ]:
a[::2]

Slicing to compute differences
------------------------------
In this example, we have an array full of odometer readings from a roadtrip through Texas.  We can use slicing and simple math to determine how far we drove on each day.

In [ ]:
od = array([21000, 21180, 21240, 22100, 22400])
dist = od[1:] - od[:-1]
dist

Simple Speed Comparison
-----------------------

Let's do a quick comparison using the magic command `%timeit` in ipython to see how much faster calculations using NumPy slicing.  For this simple example, on a Mac Book Pro, NumPy slicing is about 200x faster than the equivalent list comprehension. 

In [3]:
a = arange(1000)
%timeit a[1:] - a[:-1]

The slowest run took 323.60 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.05 µs per loop


In [4]:
% timeit [a[i+1] - a[i] for i in range(999)]

1000 loops, best of 3: 321 µs per loop


Copyright 2008-2016, Enthought, Inc.<br>Use only permitted under license.  Copying, sharing, redistributing or other unauthorized use strictly prohibited.<br>
http://www.enthought.com