# 1D Fancy Slicing (Fancy Indexing)

In [1]:
# Imports required but not shown in the video lecture.
import numpy

from numpy import array, arange
from numpy.random import rand

In [ ]:
print numpy.__version__

Fancy slicing, also called fancy indexing, allows you to select multiple items out of an array based on a sequence of indices or a boolean mask that specifies which values to retrieve.  We'll start with a simple integer array, `a`. 

In [2]:
a = arange(0, 80, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

## Using Indices

Now, specify list of indices, which can include both positive and negative values.  This sequence can then be passed into the index operator to retrieve the values at the specified indices.

*Note: There is one caveat here.  The sequence can be a list or an array, but it cannot be a tuple. This strange limitation stems from NumPy's special interpretation of tuples when indexing.  Instead of treating each entry of a tuple as an index into one axis, they are instead interpreted as indexing a multi-dimensional array.*

In [3]:
indices = [1,2,-3]

In [4]:
y = a[indices]
y

array([10, 20, 50])

## Using Boolean Masks

It's also possible to use a mask of True/False values that is the same length (or shorter) than `a` to select values out of it.  The mask *must* be an array of `dtype=bool` in order to be interpreted as a mask.  Otherwise, it will be interpreted as indices. 

*Exercise for the reader: If you leave of the `dtype=bool` what do you think will be returned.  Try it.  Did it do what you expected?  Can you explain the results?*   

In [5]:
mask = array([0,1,1,0,0,1,0,0],dtype=bool)

In [6]:
a[mask]

array([10, 20, 50])

Most of the time, you won't specify the mask by hand (as we just did).  It is much more common to create a boolean mask using a comparison operation of some sort.

In [7]:
mask2 = a < 30
mask2

array([ True,  True,  True, False, False, False, False, False], dtype=bool)

In [8]:
a[mask2]

array([ 0, 10, 20])

Here is a very similar example to what is shown above, but it selects from a set of random numbers based on whether they are above or below 0.5.

In [9]:
%precision 3
a = rand(10)
a

array([ 0.416,  0.156,  0.811,  0.392,  0.757,  0.243,  0.257,  0.084,
        0.461,  0.596])

In [10]:
a>.5

array([False, False,  True, False,  True, False, False, False, False,  True], dtype=bool)

In [11]:
mask = a>.5

In [12]:
a[mask]

array([ 0.811,  0.757,  0.596])

Copyright 2008-2016, Enthought, Inc.<br>Use only permitted under license.  Copying, sharing, redistributing or other unauthorized use strictly prohibited.<br>
http://www.enthought.com