# Using the where() function

In [1]:
# Imports required but not shown in the video lecture.
import numpy

from numpy import array, arange, where

In [ ]:
print numpy.__version__

The where() function will return the indices of every element in an array where the value is non-zero.  First, let's look at one dimensional arrays to get our feet wet with it.

In [2]:
a = array([0, 12, 5, 20])

If we want to know which elements of an array are greater than 10, we can use a comparison to generate a True/False mask indicating which values are greater than 10.

In [3]:
a>10

array([False,  True, False,  True], dtype=bool)

If, instead, we want to know the indices of the elements that are greater than 10, the `where()` comes in handy.  It will return the indices of all non-zero values.

In [4]:
where(a>10)

(array([1, 3]),)

That is pretty handy.  But, be careful!  Notice that the return value is a tuple that contains the indices as its first element.  This is due to the fact that a could be multi-dimensional, and `where` needs to be able to return, in the case of two dimensional arrays, an array of row *and* an array of column indices.  But, in truth, this is a bit of a pain for working with one dimensional arrays where you just want to get the index array back.  It is your job to pull it out.

There are a couple of common ways to do this.  

In [5]:
indices = where(a>10)
indices = indices[0]
indices

array([1, 3])

In [ ]:
# or
indices = where(a>10)[0]
indices

## Multi-dimensional arrays

Here we have a two dimensional array that demonstrates how the row and column indices are returned from where for each of the non-zero elements.

In [6]:
a = array([[0, 12, 5, 20],
           [1, 2, 11, 15]])

In [7]:
loc = where(a>10)
loc

(array([0, 0, 1, 1]), array([1, 3, 2, 3]))

In [8]:
a[loc]

array([12, 20, 11, 15])

In [9]:
# or alternatively:
rows, cols = where(a>10)

In [10]:
rows

array([0, 0, 1, 1])

In [11]:
cols

array([1, 3, 2, 3])

In [ ]:
a[rows, cols]

Here is another example with two dimensional arrays (from the command line demos in the video lecture).

In [12]:
a = arange(25)
a.shape = 5,5
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
a > 12

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [14]:
where(a>12)

(array([2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4]),
 array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

Copyright 2008-2016, Enthought, Inc.<br>Use only permitted under license.  Copying, sharing, redistributing or other unauthorized use strictly prohibited.<br>http://www.enthought.com