In [2]:
import numpy as np

# N-Dimensional Array

### 1 Dimensional array

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr

array([1, 2, 3, 4, 5, 6, 7])

### 2 Dimensional array 

In [10]:
arr = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Specifying minimum dimensions

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], ndmin=2)
arr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Changing dtype of array

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=complex)
arr

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j,
       9.+0.j])

# Data types

* bool || bool_  &emsp;&emsp;(?)&emsp;&emsp; 1 byte
* int8 &emsp;&emsp;&emsp;&emsp;(i1)&emsp;&emsp; -128 to 127
* int16 &emsp;&emsp;(i2)&emsp;&emsp; -32768 to 32767
* int32 &emsp;&emsp;(i4)&emsp;&emsp; -2147483648 to 2147483647
* int64 || int_ &emsp;&emsp;(i8)&emsp;&emsp; -9223372036854775808 to 9223372036854775807
* uint8 &emsp;&emsp;(u1)&emsp;&emsp; 0 to 255
* uint16 &emsp;&emsp;(u2)&emsp;&emsp; 0 to 65535
* uint32 &emsp;&emsp;(u4)&emsp;&emsp; 0 to 4294967295
* uint64 &emsp;&emsp;(u8)&emsp;&emsp; 0 to 18446744073709551615
* float16 &emsp;&emsp;(f2)&emsp;&emsp; 1 sign bit, 5 bits exponent, 10 bits mantissa (Half precision)
* float32 &emsp;&emsp;(f4)&emsp;&emsp; 1 sign bit, 8 bits exponent, 23 bits mantissa (Single precision)
* float64 || float_ &emsp;&emsp;(f8)&emsp;&emsp; 1 sign bit, 11 bits exponent, 52 bits mantissa (Double precision)
* str || str_ &emsp;&emsp;(U30)&emsp;&emsp; 30=no of characters
* bytes_ &emsp;&emsp;(S30)&emsp;&emsp; 30=no of bytes

### dtype object

In [13]:
dt = np.dtype(np.int64)
dt

dtype('int64')

### dtype object using equivalent string

In [14]:
dt = np.dtype('i2')
dt

dtype('int16')

### structured dtype object

In [15]:
dt = np.dtype([('age', np.int16)])
dt

dtype([('age', '<i2')])

### structured dtype applied on numpy array

In [16]:
student = np.dtype([
        ('name', 'U30'),
        ('age', 'i8'),
        ('marks', 'f4')
])

In [17]:
students = np.array([
    ('Arslan Haider Sherazi', 24, 3.42),
    ('Danish Ali', 24, 2.53),
    ('Asher Butt', 24, 3.01),
    ('Babar Ali', 22, 2.97)
], dtype=student)

In [18]:
students

array([('Arslan Haider Sherazi', 24, 3.42), ('Danish Ali', 24, 2.53),
       ('Asher Butt', 24, 3.01), ('Babar Ali', 22, 2.97)],
      dtype=[('name', '<U30'), ('age', '<i8'), ('marks', '<f4')])

In [19]:
students[0]

('Arslan Haider Sherazi', 24, 3.42)

# Array Attributes
Following are the different flags of ndim array
* __C_CONTIGUOUS (C)__
   The data is in a single, C-style contiguous segment
* __F_CONTIGUOUS (F)__
   The data is in a single, Fortran-style contiguous segment
* __OWNDATA (O)__
   The array owns the memory it uses or borrows it from another object
* __WRITEABLE (W)__
   The data area can be written to. Setting this to False locks the data, making it read-only
* __ALIGNED (A)__
   The data and all elements are aligned appropriately for the hardware
* __UPDATEIFCOPY (U)__
   This array is a copy of some other array. When this array is deallocated, the base array will be updated with
   the contents of this array

In [20]:
array = np.array([
        [1, 2, 3, 4],
        [5, 6, 7, 9],
        [10, 11, 12, 13]
], dtype=np.int16)

In [21]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  9],
       [10, 11, 12, 13]], dtype=int16)

### get shape of array (rows, columns)

In [22]:
shape_of_array = array.shape
shape_of_array

(3, 4)

### resize shape of array

In [23]:
resized_array = array.reshape(4, 3)
resized_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  9, 10],
       [11, 12, 13]], dtype=int16)

### get no of dimensions of array

In [24]:
no_of_dimensions = array.ndim
no_of_dimensions

2

### get size of each element of array in bytes

In [25]:
size_of_each_element_of_array = array.itemsize
size_of_each_element_of_array

2

### get flags statuses of array

In [27]:
array_flags_statuses = array.flags
array_flags_statuses

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# Array Creation Routines

### create empty array (filled with random values as it is not initialized)

In [29]:
array = np.empty([3, 2], dtype=int)  # [3, 2] = [rows, columns] = shape of array
array

array([[0, 0],
       [0, 0],
       [0, 0]])

### create empty array filled with zeros

In [30]:
array = np.zeros([3, 2], dtype=int)
array

array([[0, 0],
       [0, 0],
       [0, 0]])

### create empty array filled with ones

In [31]:
array = np.ones([3, 2], dtype=int)
array

array([[1, 1],
       [1, 1],
       [1, 1]])

# Create Array from Existing Data

### create array from list (1D array)

In [32]:
data = [1, 2, 3, 4, 5, 6, 7]
array = np.asarray(data, dtype=int)
array

array([1, 2, 3, 4, 5, 6, 7])

### create list from list of tuples (2D array)

In [33]:
data = [(1, 2, 3), (4, 5, 6), (7, 8, 9), (10, 11, 12)]
array = np.asarray(data, dtype=float)
array

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

### create array using buffer of data

In [34]:
data = b'Arslan Haider Sherazi - Python Developer'
array = np.frombuffer(data, dtype='S1', count=21, offset=0)
array

array([b'A', b'r', b's', b'l', b'a', b'n', b' ', b'H', b'a', b'i', b'd',
       b'e', b'r', b' ', b'S', b'h', b'e', b'r', b'a', b'z', b'i'],
      dtype='|S1')

### create array from iterator object

In [36]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
iter_obj = iter(data)
array = np.fromiter(iter_obj, dtype=int, count=5)
array

array([1, 2, 3, 4, 5])

# Create Array from Numerical Ranges

### create array using numpy.arange

In [38]:
array = np.arange(start=10, stop=20, step=2, dtype=float)
array

array([10., 12., 14., 16., 18.])

In [39]:
array = np.arange(start=20, stop=40, step=4, dtype=int)
array

array([20, 24, 28, 32, 36])

### create array using numpy.linspace

In [40]:
array = np.linspace(start=10, stop=200, num=20, dtype=float)
array

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.,
       120., 130., 140., 150., 160., 170., 180., 190., 200.])

In [41]:
array = np.linspace(start=10, stop=20, num=6, endpoint=False, retstep=True)
array

(array([10.        , 11.66666667, 13.33333333, 15.        , 16.66666667,
        18.33333333]),
 1.6666666666666667)

# Array Indexing and Slicing

In [42]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [43]:
two_dim_data = np.array([
        [1, 2, 3, 4],
        [4, 5, 6, 6],
        [7, 8, 9, 7],
        [3, 9, 3, 3],
        [4, 7, 6, 9],
        [2, 8, 9, 8],
])

### basic slicing

In [44]:
s = slice(2, 8, 2)  # items from index 2 to 7 with step of 2 indexes
sliced_data = data[s]
sliced_data

array([3, 5, 7])

In [45]:
sliced_data = data[2:8:2]  # items from index 2 to 7 with step of 2 indexes
sliced_data

array([3, 5, 7])

In [47]:
sliced_data = data[2]  # items at index 2
sliced_data

3

In [48]:
sliced_data = data[3:7]  # items from index 3 to 6
sliced_data

array([4, 5, 6, 7])

In [49]:
sliced_data = data[2:]  # items from index 2 to last_index
sliced_data

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
sliced_data = data[:4]  # items from index 0 to 3
sliced_data

array([1, 2, 3, 4])

In [51]:
sliced_data = data[:-2]  # items from index 0  to last_index-2
sliced_data

array([1, 2, 3, 4, 5, 6, 7, 8])

### basic slicing on 2D data

In [52]:
sliced_data = two_dim_data[2]  # items in the 3rd row (index 2)
sliced_data

array([7, 8, 9, 7])

In [53]:
sliced_data = two_dim_data[:3]  # items from 1st to 3rd row (index 0-2)
sliced_data

array([[1, 2, 3, 4],
       [4, 5, 6, 6],
       [7, 8, 9, 7]])

In [54]:
sliced_data = two_dim_data[1:]  # items from 2nd to last row (index 1-last_index)
sliced_data

array([[4, 5, 6, 6],
       [7, 8, 9, 7],
       [3, 9, 3, 3],
       [4, 7, 6, 9],
       [2, 8, 9, 8]])

In [55]:
sliced_data = two_dim_data[1:4]  # items from 2nd row to 4th row (index 1-3)
sliced_data

array([[4, 5, 6, 6],
       [7, 8, 9, 7],
       [3, 9, 3, 3]])

In [56]:
sliced_data = two_dim_data[..., 2]  # items in column 3
sliced_data

array([3, 6, 9, 3, 6, 9])

In [57]:
sliced_data = two_dim_data[3, ...]  # items in row 4
sliced_data

array([3, 9, 3, 3])

In [58]:
sliced_data = two_dim_data[..., 1:]  # items in column 2 to last_column
sliced_data

array([[2, 3, 4],
       [5, 6, 6],
       [8, 9, 7],
       [9, 3, 3],
       [7, 6, 9],
       [8, 9, 8]])

In [59]:
sliced_data = two_dim_data[1:3, 1:3]  # items in rows 2-3 and columns 2-3
sliced_data

array([[5, 6],
       [8, 9]])

### Advanced Indexing (Integer)

In [61]:
# syntax => two_dim_array[rows, columns]. Selects element at 0,0 1,1 and 2,2
sliced_data = two_dim_data[[0, 1, 2], [0, 1, 2]]
sliced_data

array([1, 5, 9])

In [62]:
rows = np.array([[0, 1], [2, 1]])
columns = np.array([[1, 1], [1, 2]])
sliced_data = two_dim_data[rows, columns]  # [ [(0,1), (1,1)] [(2, 1), (1, 2)] ]
sliced_data

array([[2, 5],
       [8, 6]])

In [63]:
sliced_data = two_dim_data[1:4, [1, 2]]  # selects rows 2-4 and columns 1-2
sliced_data

array([[5, 6],
       [8, 9],
       [9, 3]])

###  Advanced Indexing (Boolean)

In [64]:
items_greater_than_three = two_dim_data[two_dim_data > 3]
items_greater_than_three

array([4, 4, 5, 6, 6, 7, 8, 9, 7, 9, 4, 7, 6, 9, 8, 9, 8])

In [65]:
two_dim_data = np.array([
        [np.nan, 1, 2, 3],
        [2, np.nan, 2, 3],
        [np.nan, 1, 2, 3],
        [np.nan, 1, 2, 3]
])

In [67]:
items_other_than_nan = two_dim_data[~np.isnan(two_dim_data)]
items_other_than_nan

array([1., 2., 3., 2., 2., 3., 1., 2., 3., 1., 2., 3.])

# Broadcasting
Broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations

In [3]:
array1 = np.array([
        [0, 0, 0, 0],
        [10, 20, 30, 40],
        [50, 60, 70, 80],
        [90, 90, 90, 90]
])

In [4]:
array2 = np.array([1, 1, 1, 1])

In [6]:
addition_of_arrays = array1 + array2
addition_of_arrays

array([[ 1,  1,  1,  1],
       [11, 21, 31, 41],
       [51, 61, 71, 81],
       [91, 91, 91, 91]])

# Iterating over array

In [7]:
two_dim_array = np.array([
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 3, 4, 5],
        [3, 4, 5, 6],
        [2, 9, 5, 0]
])

### iterating over array (row wise)

In [10]:
for element in np.nditer(two_dim_array):
    print(element, end=' ')

1 2 3 4 5 6 7 8 1 3 4 5 3 4 5 6 2 9 5 0 

In [11]:
for row in np.nditer(two_dim_array, flags=['external_loop'], order='C'):
    print(row, end=' ')

[1 2 3 4 5 6 7 8 1 3 4 5 3 4 5 6 2 9 5 0] 

###  iterating over array (column wise)

In [12]:
for element in np.nditer(two_dim_array, order='F'):
    print(element, end=' ')

1 5 1 3 2 2 6 3 4 9 3 7 4 5 5 4 8 5 6 0 

In [13]:
for column in np.nditer(two_dim_array, flags=['external_loop'], order='F'):
    print(column, end=' ')

[1 5 1 3 2] [2 6 3 4 9] [3 7 4 5 5] [4 8 5 6 0] 

### modifying array values using np.nditer()

In [14]:
for element in np.nditer(two_dim_array, op_flags = ['readwrite']):
    element[...] = element + 1
two_dim_array

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [ 2,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 3, 10,  6,  1]])

### broadcasting iteration (iteration over two broadcastable arrays)

In [15]:
array1 = np.array([
        [0, 5, 10, 15],
        [20, 25, 30, 35],
        [40, 45, 50, 55]
])

In [16]:
array2 = np.array([1, 2, 3, 4])

In [17]:
for element1, element2 in np.nditer([array1, array2]):
    print('%d:%d' % (element1, element2), end=' ')

0:1 5:2 10:3 15:4 20:1 25:2 30:3 35:4 40:1 45:2 50:3 55:4 

# Binary Operators
* All results and inputs are in decimal format
* Binary operators convert inputs into binary form, apply operation on inputs and then convert the binary result
into decimal

### bit wise and operator

In [18]:
result = np.bitwise_and(14, 13)
result

12

### bit wise or operator

In [19]:
result = np.bitwise_or(14, 13)
result

15

### bit wise not (for signed integers 2's complement is calculated)

In [20]:
result = np.bitwise_not(np.array([13], dtype=np.uint8))  # equivalent => np.invert(np.array([13], dtype=np.uint8))
result

array([242], dtype=uint8)

In [21]:
result = np.bitwise_not(-13)  # equivalent => np.invert(-13)
result

12

### left shift

In [22]:
result = np.left_shift(12, 2)  # left shift 12 by 2 position
result

48

### right shift

In [23]:
result = np.right_shift(12, 2)  # right shift 12 by 2 position
result

3

# Array Manipulation

In [24]:
one_dim_array = np.array([1, 2, 3, 4, 2, 6, 7, 7, 9])

In [25]:
two_dim_array = np.array([
        [11, 22, 33],
        [44, 55, 66],
        [77, 88, 99],
        [33, 33, 33],
        [67, 67, 67]
])

### Convert 1D array into 2D array

In [26]:
reshaped_one_dim_array = one_dim_array.reshape(3, 3)
reshaped_one_dim_array

array([[1, 2, 3],
       [4, 2, 6],
       [7, 7, 9]])

### convert 2D array into 1D array

In [27]:
two_dim_array_into_one_dim_array = two_dim_array.flatten(order='F')
two_dim_array_into_one_dim_array

array([11, 44, 77, 33, 67, 22, 55, 88, 33, 67, 33, 66, 99, 33, 67])

In [28]:
array_element_in_two_dim_array = two_dim_array.flat[2]  # 2 = index no
array_element_in_two_dim_array

33

### find transpose of 2D array

In [29]:
transpose = np.transpose(two_dim_array)
transpose

array([[11, 44, 77, 33, 67],
       [22, 55, 88, 33, 67],
       [33, 66, 99, 33, 67]])

In [30]:
transpose = two_dim_array.T
transpose

array([[11, 44, 77, 33, 67],
       [22, 55, 88, 33, 67],
       [33, 66, 99, 33, 67]])

### concatenate arrays

In [31]:
array1 = np.array([[1,2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenate_arrays = np.concatenate((array1, array2))
concatenate_arrays

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
concatenate_arrays = np.concatenate((array1, array2), axis=1)
concatenate_arrays

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Splitting the array into sub arrays

In [33]:
sub_arrays = np.split(one_dim_array, 3)
for array in sub_arrays:
    print(array, end=' ')

[1 2 3] [4 2 6] [7 7 9] 

In [35]:
sub_arrays = np.split(two_dim_array, 3, axis=1)
for array in sub_arrays:
    print(array)

[[11]
 [44]
 [77]
 [33]
 [67]]
[[22]
 [55]
 [88]
 [33]
 [67]]
[[33]
 [66]
 [99]
 [33]
 [67]]


### append values in 1D array

In [36]:
new_one_dim_array = np.append(one_dim_array, 10)
new_one_dim_array

array([ 1,  2,  3,  4,  2,  6,  7,  7,  9, 10])

### append rows/columns in 2D array

In [37]:
new_two_dim_array = np.append(two_dim_array, [[88, 88, 88]], axis=0)  # append row
new_two_dim_array

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99],
       [33, 33, 33],
       [67, 67, 67],
       [88, 88, 88]])

In [38]:
# append column
new_two_dim_array = np.append(two_dim_array, [[88, 88, 88], [88, 88, 88], [88, 88, 88], [88, 88, 88], [88, 88, 88]], axis=1)
new_two_dim_array

array([[11, 22, 33, 88, 88, 88],
       [44, 55, 66, 88, 88, 88],
       [77, 88, 99, 88, 88, 88],
       [33, 33, 33, 88, 88, 88],
       [67, 67, 67, 88, 88, 88]])

### insert value at specific index in 1D array

In [39]:
# 1=index, 22=value to be inserted at given index
new_one_dim_array = np.insert(one_dim_array, 1, 22)
new_one_dim_array  # all other values are shifted one index forward

array([ 1, 22,  2,  3,  4,  2,  6,  7,  7,  9])

### insert rows/columns at specific index in 2D array

In [40]:
new_two_dim_array = np.insert(two_dim_array, 1, [11, 11, 11], axis=0)  # inserts new row
new_two_dim_array

array([[11, 22, 33],
       [11, 11, 11],
       [44, 55, 66],
       [77, 88, 99],
       [33, 33, 33],
       [67, 67, 67]])

In [41]:
new_two_dim_array = np.insert(two_dim_array, 0, [0, 0, 0, 0, 0], axis=1)  # inserts new column
new_two_dim_array

array([[ 0, 11, 22, 33],
       [ 0, 44, 55, 66],
       [ 0, 77, 88, 99],
       [ 0, 33, 33, 33],
       [ 0, 67, 67, 67]])

### delete value at specific index of 1D array

In [42]:
new_one_dim_array = np.delete(one_dim_array, 2)  # 2=index whose value t be deleted
new_one_dim_array

array([1, 2, 4, 2, 6, 7, 7, 9])

### delete rows/columns at specific index of 2D array

In [43]:
new_two_dim_array = np.delete(two_dim_array, 2, axis=0)  # deletes row
new_two_dim_array

array([[11, 22, 33],
       [44, 55, 66],
       [33, 33, 33],
       [67, 67, 67]])

In [44]:
new_two_dim_array = np.delete(two_dim_array, 2, axis=1)  # deletes column
new_two_dim_array

array([[11, 22],
       [44, 55],
       [77, 88],
       [33, 33],
       [67, 67]])

### find unique elements from array

In [45]:
unique_one_dim_array_elements = np.unique(one_dim_array)
unique_one_dim_array_elements

array([1, 2, 3, 4, 6, 7, 9])

In [46]:
# first converts 2D array into 1D array then find unique elements
unique_two_dim_array_elements = np.unique(two_dim_array) 
unique_two_dim_array_elements

array([11, 22, 33, 44, 55, 66, 67, 77, 88, 99])

### find indices of unique elements of array

In [47]:
unique_elements, unique_elements_indices = np.unique(one_dim_array, return_index=True)
unique_elements_indices

array([0, 1, 2, 3, 5, 6, 8])

In [48]:
# first converts 2D array into 1D array then find unique indices
unique_elements, unique_elements_indices = np.unique(two_dim_array, return_index=True)
unique_elements_indices

array([ 0,  1,  2,  3,  4,  5, 12,  6,  7,  8])

### find the count of repetitions of unique elements

In [49]:
unique_elements, unique_elements_count = np.unique(one_dim_array, return_counts=True)
unique_elements_count

array([1, 2, 1, 1, 1, 2, 1])

In [50]:
# first converts 2D array into 1D array then find unique elements count 
unique_elements, unique_elements_count = np.unique(two_dim_array, return_counts=True) 
unique_elements_count

array([1, 1, 4, 1, 1, 1, 3, 1, 1, 1])

### reconstruct the original array from unique indices

In [51]:
unique_elements, unique_elements_indices = np.unique(one_dim_array, return_inverse=True)
unique_elements_indices

array([0, 1, 2, 3, 1, 4, 5, 5, 6])

In [52]:
# first converts 2D array into 1D array then find unique indices 
unique_elements, unique_elements_indices = np.unique(two_dim_array, return_inverse=True)
original_array = unique_two_dim_array_elements[unique_elements_indices]
original_array

array([11, 22, 33, 44, 55, 66, 77, 88, 99, 33, 33, 33, 67, 67, 67])

# Mathematical Functions

In [3]:
angles = np.array([0, 30, 45, 60, 90])
decimal_array = [1.2222, 2.3333, 4.6785, 2.6666666666, 6.7891234567, 6.089765432]

### find sin, cos and tan of angles

In [4]:
sin_of_angles = np.sin(angles * np.pi / 180)
sin_of_angles

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [5]:
cos_of_angles = np.cos(angles * np.pi / 180)
cos_of_angles

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [6]:
tan_of_angles = np.tan(angles * np.pi / 180)
tan_of_angles

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

### find inverse sin, cos and tan of angles

In [7]:
inverse_sin_of_angles = np.arcsin(sin_of_angles)
inverse_sin_of_angles

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [8]:
inverse_cos_of_angles = np.arccos(cos_of_angles)
inverse_cos_of_angles

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [9]:
inverse_tan_of_angles = np.arctan(tan_of_angles)
inverse_tan_of_angles

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

### round decimal values to specified precision

In [10]:
rounded_array = np.round(decimal_array, decimals=2)
rounded_array

array([1.22, 2.33, 4.68, 2.67, 6.79, 6.09])

### find floor of decimal values

In [11]:
array_with_floor_values = np.floor(decimal_array)
array_with_floor_values

array([1., 2., 4., 2., 6., 6.])

### find ceil of decimal values

In [12]:
array_with_ceil_values = np.ceil(decimal_array)
array_with_ceil_values

array([2., 3., 5., 3., 7., 7.])

# Arithmetic Functions

In [13]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])    

### addition of arrays

In [14]:
addition = np.add(array1, array2)
addition

array([ 6,  8, 10, 12])

### subtraction of arrays

In [16]:
subraction = np.subtract(array1, array2)
subraction

array([-4, -4, -4, -4])

### multiplication of arrays

In [17]:
multiplication = np.multiply(array1, array2)
multiplication

array([ 5, 12, 21, 32])

### division of arrays

In [18]:
division = np.divide(array1, array2)
division

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

### remainder/mod of arrays division

In [19]:
remainder = np.mod(array1, array2)  # equivalent => np.remainder(array1, array2)
remainder

array([1, 2, 3, 4])

### reciprocal of array

In [20]:
reciprocal = np.reciprocal(array1)
reciprocal

array([1, 0, 0, 0])

### array1 ^ array2

In [21]:
power = np.power(array1, array2)
power

array([    1,    64,  2187, 65536])

# String Functions

In [23]:
array1 = ['Syed', 'arslan']
array2 = [' haider', ' sherazi']

### concatenate string arrays

In [24]:
array = np.char.add(array1, array2)
array

array(['Syed haider', 'arslan sherazi'], dtype='<U14')

### repeat string (multiply string by a number)

In [25]:
array = np.char.multiply(array1, 2)
array

array(['SyedSyed', 'arslanarslan'], dtype='<U12')

In [26]:
strings = np.char.multiply('Arslan ', 5)
strings

array('Arslan Arslan Arslan Arslan Arslan ', dtype='<U35')

### moving string at center by filling left and right with some character

In [27]:
centered_array = np.char.center(array1, 20, fillchar='*')
centered_array

array(['********Syed********', '*******arslan*******'], dtype='<U20')

In [28]:
centered_string = np.char.center('Arslan', 20, fillchar='#')
centered_string

array('#######Arslan#######', dtype='<U20')

### capitalize string first letter

In [29]:
capitalized_string = np.char.capitalize('haider')
capitalized_string

array('Haider', dtype='<U6')

### capitalize first letter of each word of string

In [30]:
capitalized_array = np.char.title(array2)
capitalized_array

array([' Haider', ' Sherazi'], dtype='<U8')

In [31]:
capitalized_string = np.char.title('arslan haider sherazi')
capitalized_string

array('Arslan Haider Sherazi', dtype='<U21')

### convert string characters into lower case

In [32]:
lower_array = np.char.lower(['ARSLAn', 'HAIDER'])  # it calls str.lower for every character
lower_array

array(['arslan', 'haider'], dtype='<U6')

In [33]:
lower_string = np.char.lower('HAIDER')
lower_string

array('haider', dtype='<U6')

### convert string characters into upper case

In [34]:
upper_array = np.char.upper(['arslan', 'HaiDer'])  # it calls str.upper for every character
upper_array

array(['ARSLAN', 'HAIDER'], dtype='<U6')

In [36]:
upper_string = np.char.upper('HaideR')
upper_string

array('HAIDER', dtype='<U6')

### split string by separator(white space is the default separator)

In [37]:
string_array = np.char.split('Arslan Haider Sherazi')
string_array

array(list(['Arslan', 'Haider', 'Sherazi']), dtype=object)

In [38]:
string_array = np.char.split('Arslan-Haider-Sherazi', sep='-')
string_array

array(list(['Arslan', 'Haider', 'Sherazi']), dtype=object)

### split string by line

In [39]:
string_array = np.char.splitlines('Arslan\nHaider\nSherazi')
string_array

array(list(['Arslan', 'Haider', 'Sherazi']), dtype=object)

### remove specified charcter from string from head/tail if present

In [40]:
stripped_string_array = np.char.strip(['arslan', 'akram', 'anil'], 'a')
stripped_string_array

array(['rslan', 'kram', 'nil'], dtype='<U6')

In [41]:
stripped_string = np.char.strip('arslan', 'n')
stripped_string

array('arsla', dtype='<U6')

### separate string characters by specified separator

In [42]:
separated_string_array = np.char.join(['-', ':'], ['Arslan', 'Haider'])
separated_string_array

array(['A-r-s-l-a-n', 'H:a:i:d:e:r'], dtype='<U11')

In [43]:
separated_string_array = np.char.join(['-', ':'], ['Arslan', 'Haider'])
separated_string_array

array(['A-r-s-l-a-n', 'H:a:i:d:e:r'], dtype='<U11')

### replace string word by another word

In [44]:
replaced_string_array = np.char.replace(['There were a crow', 'He were very thirsty'], 'were', 'was')
replaced_string_array

array(['There was a crow', 'He was very thirsty'], dtype='<U19')

In [45]:
replaced_string = np.char.replace('There were a crow', 'were', 'was')
replaced_string

array('There was a crow', dtype='<U16')

### encode and decode string (default encoding scheme is utf_8) => calls str.encode and str.decode for every element

In [46]:
encoded_string_array = np.char.encode(['Arslan', 'Haider', 'Sherazi'], 'cp500')  # cp500=encoding scheme
encoded_string_array

array([b'\xc1\x99\xa2\x93\x81\x95', b'\xc8\x81\x89\x84\x85\x99',
       b'\xe2\x88\x85\x99\x81\xa9\x89'], dtype='|S7')

In [47]:
decoded_string_array = np.char.decode(encoded_string_array, 'cp500')
decoded_string_array

array(['Arslan', 'Haider', 'Sherazi'], dtype='<U7')

In [48]:
encoded_string = np.char.encode('Arslan Haider Sherazi', 'cp500')
encoded_string

array(b'\xc1\x99\xa2\x93\x81\x95@\xc8\x81\x89\x84\x85\x99@\xe2\x88\x85\x99\x81\xa9\x89',
      dtype='|S21')

In [49]:
decoded_string = np.char.decode(encoded_string, 'cp500')
decoded_string

array('Arslan Haider Sherazi', dtype='<U21')

# Statistical Functions
__If we apply any statistical function on 2D array without specifying axis then 2D array will be converted into 1D
array and after that statistical function will be applied on that converted 1D array__

In [50]:
two_dim_array = np.array([
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [7, 8, 9, 0],
        [0, 0, 1, 1],
        [0, 0, 0, 0],
        [1, 4, 5, 7]
 ])

### find minimum & maximum values from rows

In [51]:
min_values = np.amin(two_dim_array, 1)
min_values

array([1, 5, 0, 0, 0, 1])

In [52]:
max_values = np.amax(two_dim_array, 1)
max_values

array([4, 8, 9, 1, 0, 7])

### find minimum & maximum values from columns

In [53]:
min_values = np.amin(two_dim_array, 0)
min_values

array([0, 0, 0, 0])

In [54]:
max_values = np.amax(two_dim_array, 0)
max_values

array([7, 8, 9, 8])

### find percentile

In [55]:
percentile_of_2D_array = np.percentile(two_dim_array, 50)
percentile_of_2D_array

2.5

In [56]:
percentile_of_2D_array_rows = np.percentile(two_dim_array, 50, axis=1)
percentile_of_2D_array_rows

array([2.5, 6.5, 7.5, 0.5, 0. , 4.5])

In [57]:
percentile_of_2D_array_columns = np.percentile(two_dim_array, 50, axis=0)
percentile_of_2D_array_columns

array([1. , 3. , 4. , 2.5])

### find mean

In [58]:
mean_of_2D_array = np.mean(two_dim_array)
mean_of_2D_array

3.2916666666666665

In [59]:
mean_of_2D_array_rows = np.mean(two_dim_array, axis=1)
mean_of_2D_array_rows

array([2.5 , 6.5 , 6.  , 0.5 , 0.  , 4.25])

In [60]:
mean_of_2D_array_columns = np.mean(two_dim_array, axis=0)
mean_of_2D_array_columns

array([2.33333333, 3.33333333, 4.16666667, 3.33333333])

### find median

In [61]:
median_of_2D_array = np.median(two_dim_array)
median_of_2D_array

2.5

In [62]:
median_of_2D_array_rows = np.median(two_dim_array, axis=1)
median_of_2D_array_rows

array([2.5, 6.5, 7.5, 0.5, 0. , 4.5])

In [63]:
median_of_2D_array_columns = np.median(two_dim_array, axis=0)
median_of_2D_array_columns

array([1. , 3. , 4. , 2.5])

### find average

In [64]:
average_of_2D_array = np.average(two_dim_array)
average_of_2D_array

3.2916666666666665

In [65]:
average_of_2D_array_rows = np.average(two_dim_array, axis=1)
average_of_2D_array_rows

array([2.5 , 6.5 , 6.  , 0.5 , 0.  , 4.25])

In [66]:
average_of_2D_array_columns = np.average(two_dim_array, axis=0)
average_of_2D_array_columns

array([2.33333333, 3.33333333, 4.16666667, 3.33333333])

In [67]:
average_of_2D_array_rows_against_weights = np.average(two_dim_array, weights=[2, 3, 4, 5], axis=1)
average_of_2D_array_rows_against_weights

array([2.85714286, 6.85714286, 5.28571429, 0.64285714, 0.        ,
       4.92857143])

### find variance

In [68]:
variance_of_2D_array = np.var(two_dim_array)
variance_of_2D_array

9.62326388888889

In [69]:
variance_of_2D_array_rows = np.var(two_dim_array, axis=1)
variance_of_2D_array_rows

array([ 1.25  ,  1.25  , 12.5   ,  0.25  ,  0.    ,  4.6875])

In [70]:
variance_of_2D_array_columns = np.var(two_dim_array, axis=0)
variance_of_2D_array_columns

array([ 7.22222222,  8.88888889, 10.13888889, 10.55555556])

### find standard deviation

In [71]:
std_of_2D_array = np.std(two_dim_array)
std_of_2D_array

3.102138599239062

In [72]:
std_of_2D_array_rows = np.std(two_dim_array, axis=1)
std_of_2D_array_rows

array([1.11803399, 1.11803399, 3.53553391, 0.5       , 0.        ,
       2.16506351])

In [73]:
std_of_2D_array_columns = np.std(two_dim_array, axis=0)
std_of_2D_array_columns

array([2.68741925, 2.98142397, 3.1841622 , 3.24893145])

# Searching Array

In [74]:
two_dim_array = np.array([
        [2, 3, 1, 5],
        [6, 7, 8, 2],
        [8, 0, 2, 4]
])

### find index of maximum and minimum value from 2D array

In [75]:
index_of_maximum_value = np.argmax(two_dim_array)
index_of_maximum_value

6

In [76]:
index_of_minimum_value = np.argmin(two_dim_array)
index_of_minimum_value

9

### find indices of maximum and minimum values from 2D array (rows)

In [77]:
indices_of_maximum_value_in_rows = np.argmax(two_dim_array, axis=1)
indices_of_maximum_value_in_rows

array([3, 2, 0])

In [78]:
indices_of_minimum_value_in_rows = np.argmin(two_dim_array, axis=1)
indices_of_minimum_value_in_rows

array([2, 3, 1])

### find indices of maximum and minimum values from 2D array (columns)

In [79]:
indices_of_maximum_value_in_columns = np.argmax(two_dim_array, axis=0)
indices_of_maximum_value_in_columns

array([2, 1, 1, 0])

In [80]:
indices_of_minimum_value_in_columns = np.argmin(two_dim_array, axis=0)
indices_of_minimum_value_in_columns

array([0, 2, 0, 1])

### find indices of non zero values of array

In [81]:
indices_of_non_zero_elements = np.nonzero(two_dim_array)
indices_of_non_zero_elements

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 2, 3]))

### find indices of values satisfying specific condition (values greater than 3)

In [82]:
indices_of_values_greater_than_3 = np.where(two_dim_array > 3)
indices_of_values_greater_than_3

(array([0, 1, 1, 1, 2, 2]), array([3, 0, 1, 2, 0, 3]))

### find values satisfying specific condition (mode with 2 is 0)

In [83]:
condition = np.mod(two_dim_array, 2) == 0
values_whose_mod_with_2_is_0 = np.extract(condition, two_dim_array)
values_whose_mod_with_2_is_0

array([2, 6, 8, 2, 8, 0, 2, 4])

### get array elements from indices

In [84]:
array_elements = two_dim_array[indices_of_values_greater_than_3]
array_elements

array([5, 6, 7, 8, 8, 4])

# Sorting Array
* __quick sort is default sorting algorithm if not specified__
* __default axis is 1 (rows)__

In [85]:
one_dim_array = np.array([2, 5, 1, 3, 0, 2, 9, 8])

In [86]:
two_dim_array = np.array([
    [1, 9, 0, 4],
    [8, 5, 6, 1],
    [6, 4, 0, 2]
])

In [87]:
dt = np.dtype([('name', 'U20'), ('age', int)])

In [88]:
dt_array = np.array([
        ('Waqar', 29),
        ('Arslan', 24),
        ('Fasi', 26),
        ('Haider', 18)
], dtype=dt)

### sorting 1D array

In [89]:
sorted_array = np.sort(one_dim_array, kind='heapsort')
sorted_array

array([0, 1, 2, 2, 3, 5, 8, 9])

### sorting array by rows

In [90]:
sorted_array = np.sort(two_dim_array)
sorted_array

array([[0, 1, 4, 9],
       [1, 5, 6, 8],
       [0, 2, 4, 6]])

### sorting array by columns

In [91]:
sorted_array = np.sort(two_dim_array, axis=0, kind='mergesort')
sorted_array

array([[1, 4, 0, 1],
       [6, 5, 0, 2],
       [8, 9, 6, 4]])

### sorting by order when values of different data types are present in array

In [92]:
sorted_array = np.sort(dt_array, order='name')
sorted_array

array([('Arslan', 24), ('Fasi', 26), ('Haider', 18), ('Waqar', 29)],
      dtype=[('name', '<U20'), ('age', '<i8')])

### find indices of sorted elements of 1D array

In [93]:
sorted_array_indices = np.argsort(one_dim_array)
sorted_array_indices

array([4, 2, 0, 5, 3, 1, 7, 6])

### find indices of sorted elements of 2D arrays (rows)

In [94]:
sorted_array_indices = np.argsort(two_dim_array)
sorted_array_indices

array([[2, 0, 3, 1],
       [3, 1, 2, 0],
       [2, 3, 1, 0]])

### find indices of sorted elements of 2D arrays (columns)

In [95]:
sorted_array_indices = np.argsort(two_dim_array, axis=0)
sorted_array_indices

array([[0, 2, 0, 1],
       [2, 1, 2, 2],
       [1, 0, 1, 0]])

# Copying Array
* __When content of an array is stored physically on another location then it is called copy of that array__
* __If different view of same memory location content is provided then it is called view__
* __Slice of an array creates a view.__

In [155]:
array = np.array([1, 2, 3, 5])

### simple assignment (change in one array reflects on both arrays)

In [156]:
assigned_array = array
assigned_array

array([1, 2, 3, 5])

In [157]:
array[0] = 10
array

array([10,  2,  3,  5])

In [158]:
assigned_array

array([10,  2,  3,  5])

### view of array (change in one array reflects on both arrays)

In [159]:
array_view = array.view()
array

array([10,  2,  3,  5])

In [160]:
array[0] = 60

In [161]:
array

array([60,  2,  3,  5])

In [162]:
array_view

array([60,  2,  3,  5])

### deep copy of array

In [163]:
array_deep_copy = array.copy()

In [164]:
array

array([60,  2,  3,  5])

In [165]:
array[0] = 70
array

array([70,  2,  3,  5])

In [166]:
array_deep_copy

array([60,  2,  3,  5])

# Byte Swapping
* __byteswap() function toggles between low-endian and big-endian data representation.__
* __low-endian & big-endian https://www.geeksforgeeks.org/little-and-big-endian-mystery/__
* __string arrays cannot not be byte swapped__

In [167]:
array = np.array([100, 23, 456])
array

array([100,  23, 456])

In [168]:
list(map(hex, array))

['0x64', '0x17', '0x1c8']

### byte swapping of array

In [169]:
byte_swapped_array = array.byteswap(inplace=True)
byte_swapped_array

array([ 7205759403792793600,  1657324662872342528, -4034943791147253760])

In [170]:
list(map(hex, byte_swapped_array))

['0x6400000000000000', '0x1700000000000000', '-0x37ff000000000000']

# Linear Algebra

In [171]:
one_dim_array1 = np.array([1, 2, 3, 4, 4, 6])
one_dim_array2 = np.array([7, 8, 9, 2, 1, 5])

In [172]:
two_dim_array1 = np.array([
        [1, 2, 3],
        [5, 6, 7],
        [9, 0, 1]
])

In [173]:
two_dim_array2 = np.array([
        [2, 4, 5],
        [7, 8, 9],
        [1, 2, 3]
])

### dot product of arrays

In [174]:
dot_product_of_one_dim_arrays = np.dot(one_dim_array1, one_dim_array2)
dot_product_of_one_dim_arrays

92

###  dot product of arrays

In [175]:
dot_product_of_two_dim_arrays = np.dot(two_dim_array1, two_dim_array2)
dot_product_of_two_dim_arrays

array([[ 19,  26,  32],
       [ 59,  82, 100],
       [ 19,  38,  48]])

###  inner product of arrays

In [176]:
inner_product_of_one_dim_arrays = np.inner(one_dim_array1, one_dim_array2)
inner_product_of_one_dim_arrays

92

In [177]:
inner_product_of_two_dim_arrays = np.inner(two_dim_array1, two_dim_array2)
inner_product_of_two_dim_arrays

array([[ 25,  50,  14],
       [ 69, 146,  38],
       [ 23,  72,  12]])

### determinant of two matrix/ndarray

In [178]:
determinant = np.linalg.det(two_dim_array1)
determinant

-40.000000000000014

### inverse of two matrix/ndarray

In [179]:
inverse = np.linalg.inv(two_dim_array1)
inverse

array([[-0.15,  0.05,  0.1 ],
       [-1.45,  0.65, -0.2 ],
       [ 1.35, -0.45,  0.1 ]])

# Matrix library
* __np.matlib library returns matrices instead of ndarray objects__
* __matrix is always two-dimensional, whereas ndarray is an n-dimensional array. Both the objects are
  inter-convertible.__

In [181]:
import numpy.matlib as matlib

### create empty matrix (filled with random data)

In [182]:
empty_matrix = matlib.empty((2, 2))
empty_matrix

matrix([[-1.72723371e-077,  1.49457272e-154],
        [ 1.52782695e+160,  3.27691607e-309]])

### create matrix filled with zeros

In [183]:
zeros_matrix = matlib.zeros((2, 2))
zeros_matrix

matrix([[0., 0.],
        [0., 0.]])

### create matrix filled with ones

In [184]:
ones_matrix = matlib.ones((2, 2))
ones_matrix

matrix([[1., 1.],
        [1., 1.]])

### create identity matrix

In [185]:
identity_matrix = matlib.identity(4, dtype=int)
identity_matrix

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

### create matrix filled with random values

In [186]:
random_matrix = matlib.rand((4, 4))
random_matrix

matrix([[0.19861592, 0.7405093 , 0.15235562, 0.84641692],
        [0.9395423 , 0.49487517, 0.63285296, 0.67377354],
        [0.95109317, 0.38757072, 0.71221479, 0.76602822],
        [0.47562156, 0.10841118, 0.43440346, 0.10361592]])

### create scalar matrix (1 at diagonal and 0 at other places)

In [187]:
scalar_matrix = matlib.eye(n=3, M=4, k=0, dtype=int)
scalar_matrix

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0]])

### convert matrix into nd array

In [188]:
matrix = matlib.rand((2, 2))
array = np.asarray(matrix)

In [189]:
type(matrix)

numpy.matrix

In [190]:
matrix

matrix([[0.29313197, 0.96529072],
        [0.4026731 , 0.93635619]])

In [191]:
type(array)

numpy.ndarray

In [192]:
array

array([[0.29313197, 0.96529072],
       [0.4026731 , 0.93635619]])

### convert nd array into matrix

In [193]:
array = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
])

In [194]:
matrix = np.asmatrix(array)

In [195]:
type(array)

numpy.ndarray

In [196]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [197]:
type(matrix)

numpy.matrix

In [198]:
matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Input / Output Array

In [199]:
array = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
])

### saving array into binary file

In [200]:
np.save('output_file', array)

### loading array from binary file

In [202]:
array = np.load('output_file.npy')
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### saving array into text file

In [203]:
np.savetxt('output_file.txt', array)

### loading array from text file

In [205]:
array = np.loadtxt('output_file.txt')
array

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])